### ISSUE TITLE
Nathan 

### ISSUE THREAD

**Issue by momoladebrouill** [momoladebrouill/momoladebrouill.github.io#8]
Depuis que j'ai appris que l'humanité entière est peut être bâti sur un mensonge, je me prend toutes les chaises

**Comment by Ravelfett** [comment]
comme le dit javascript
![image](https://user-images.githubusercontent.com/41432535/139335140-1b28fc68-0c44-426b-867f-bfc64e176fa6.png)

**Comment by momoladebrouill** [comment]
Le javascript : une source d'inspiration
![iikea](https://user-images.githubusercontent.com/76487368/139416909-8f9de2aa-a8a3-47b1-9cba-714d9ae9a79b.png)
